# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Yurii Cherkasov
title: Senior Software Engineer
email: yurii.cherkasov@protonmail.com
website: https://github.com/yuchdev/

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  yuchdev
xing_username: atatat

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs

  Dedicated software engineer, having more than a decade of experience in software design and development. My job is my passion and hobby. My biggest expertise is C++/Python, separately or together, with these technologies and my interest to create high-quality software, I can create almost everything.

  I supported legacy systems, implemented new systems, and designed them from scratch.

  I have experience both in enterprise and in startups.

  I was setting up development processes and workflows, Agile/Scrum, code review, Continuous Integration, and task tracking, managed a team of Software Engineers, DevOps, and QAs.

  You can take a look at examples of my code on Github, so that get some view of the coding standards I'm keeping during my daily work, and insist to be implemented within my team:

  [Probabilistic calculator, checking whether the file encrypted or not](https://github.com/yuchdev/entropy_calculator)

  [Simple multi-threaded password bruteforcer for MD5 hash (with educational purpose only!)](https://github.com/yuchdev/md5bruteforcer)

  [Generator of program code](https://github.com/yuchdev/code_generator)

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: The comprehensive catalog of C++ books
        link: https://github.com/yuchdev/CppBooks
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A comprehensive catalog of modern and classic books on C++ programming language
        description: | # this will include new lines to allow paragraphs
          No secret, most of the C++ books on the market are for absolute beginners, and 90% of them are bad. Few good books for intermediate-to-advanced developers, but finding and advising a good read on C++ is almost a scientific problem.
          I hope this curated book catalog would save lots of time both to C++ beginners and professionals.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: VEKTOR T13 Technologies
        link: https://vektort13.pro
        sub_title: Lead Software Engineer
        caption: December 2019 - Present
        quote: >
          IT Security Startup
        description: | # this will include new lines to allow paragraphs
            In this startup I was working on a line of products:
            * IP Auditor. Anti-fraud system for a comprehensive audit of IP addresses, providing reports
            about geographical location, connection details, and threats that could possess that IP address.
            I’m working on the server-side, developing an Anti-Fraud API Aggregator, collecting information
            from a number of 3rd-party APIs.
            * Virtualbox. Powerful opensource x86/AMD64/Intel64 virtualization product. I created my own
            branch with slight improvements over the Oracle version, implemented a cross-platform build
            toolchain, and worked on documentation.
            Programming languages, products and technologies: C, C++, Qt5, Python, PyQt, Django REST Framework, CMake, TeamCity

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

theme: jekyll-theme-cayman